### ISSUE TITLE
Give instructors access to Topic Tools

### ISSUE THREAD

**Issue by TyreceDJ** [CMU-313/fall23-nodebb-pittbegels#11]
Currently, only the admin has access to the topic tools feature which provides tools to, pin, move, and delete certain topics. Below is the feature instructors should have.

![Image](https://github.com/CMU-313/fall23-nodebb-pittbegels/assets/55469793/60890da1-303f-4b80-bc7d-10acee507bdd)

**Comment by connormaas-cmu** [comment]
We don't have time. Closing
