### ISSUE TITLE
Users unable to login.

### ISSUE THREAD

**Issue by TyreceDJ** [CMU-313/fall23-nodebb-pittbegels#31]
Unable to log in to Nodebb after documentation commits. Recreate the issue by running `git fetch` to get the newest merge and attempting to log in.

Here's the error in the console after attempting to log in.

![Image](https://github.com/CMU-313/fall23-nodebb-pittbegels/assets/55469793/93e56d0f-15ce-4583-a9c8-e3962034c382)

I believe it's caused by `check` function in public/src/client/login.js. Removing that function allowed me to log back in.

**Comment by ryan-huan** [comment]
Issue has been resolved
